language: rust
cache: cargo
rust:
- stable
sudo: required
os:
- linux

matrix:
  include:
    - name: "ARM Build"
      env: 
      - TARGET=arm-unknown-linux-gnueabihf
      - RUSTFLAGS="-C linker=arm-linux-gnueabihf-gcc -L/usr/arm-linux-gnueabihf/lib -L$TRAVIS_BUILD_DIR/deps_root/usr/lib/arm-linux-gnueabihf"
      - PKG_CONFIG_ALLOW_CROSS=1
      - OPENSSL_DIR=$TRAVIS_BUILD_DIR/deps_root/usr
      - OPENSSL_LIB_DIR=$TRAVIS_BUILD_DIR/deps_root/usr/lib/arm-linux-gnueabihf
      - OPENSSL_INCLUDE_DIR=$TRAVIS_BUILD_DIR/deps_root/usr/include/arm-linux-gnueabihf
      - SHORT_TARGET=armv6
      addons:
        apt:
          packages:
          - gcc-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
          - libasound2-dev
          - libssl-dev
          - libssl1.0.0
      before_script:
      - echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ trusty main" | sudo tee -a /etc/apt/sources.list
      - sudo apt-get update
      - sudo apt-get download libasound2:armhf
      - sudo apt-get download libasound2-dev:armhf
      - sudo apt-get download libssl-dev:armhf
      - sudo apt-get download libssl1.0.0:armhf
      - dpkg -x libasound2_*.deb $TRAVIS_BUILD_DIR/deps_root/
      - dpkg -x libssl-dev*.deb $TRAVIS_BUILD_DIR/deps_root/
      - dpkg -x libssl1.0.0*.deb $TRAVIS_BUILD_DIR/deps_root/
      - dpkg -x libasound2-dev*.deb $TRAVIS_BUILD_DIR/deps_root/

    - name: "x86 Build"
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - SHORT_TARGET=x86
       addons:
         apt:
           packages:
           - libasound2-dev
           - libssl-dev
           - libssl1.0.0      
            
script:
- rustup target add $TARGET
- cargo build --target=$TARGET --release
- zip -j spotifyd-`date --iso-8601`-$SHORT_TARGET.zip target/$TARGET/release/spotifyd

#deploy:
#  provider: releases
#  file_glob: true
#  api_key: $GITHUB_TOKEN
#  skip_cleanup: true
#  on:
#branch: arm_travis
